GET http://localhost:1234/user/read

###

POST http://localhost:1234/user/create
Content-Type: application/json

{
    "username":"annamalai",
    "encode":"sam",
    "role":"teacher",
    "email":"s.annamalai1995@gmail.com"
}

###

DELETE http://localhost:1234/user/delete/66a88fb7b781b650075bc606

###